name: Validate examples

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ajv + formats
        run: npm install -g ajv-cli ajv-formats
      - name: Validate examples
        run: ajv validate -c ajv-formats -s schemas/telemachus.schema.json -d "examples/*.json"